"""
Shared PDF-generation + email logic used by both main.py (the Flask service,
for the SSE /generate endpoint) and job_main.py (the Cloud Run Job entrypoint).
Kept in one place so the two entrypoints can't drift out of sync.
"""
import os
import smtplib
import subprocess
from email.message import EmailMessage

SCRIPT = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'recovery_report.py')


def build_env(data: dict, out_path: str) -> dict:
    env = os.environ.copy()
    env['REPORT_DATE_FROM']  = data.get('dateFrom',  '2026-04-11')
    env['REPORT_DATE_TO']    = data.get('dateTo',    '2026-04-18')
    env['REPORT_DEPOSIT_TO'] = data.get('depositTo', '') or ''

    institutions = data.get('institutions') or []
    institution  = data.get('institution',  '')
    if institutions:
        env['REPORT_INSTITUTIONS'] = ','.join(institutions)
    elif institution:
        env['REPORT_INSTITUTIONS'] = institution

    env['REPORT_OUTPUT_PATH'] = out_path
    return env


def run_script(env: dict, out_path: str, timeout: int = 3600) -> bytes:
    """Run recovery_report.py and return PDF bytes. Raises on failure."""
    result = subprocess.run(
        ['python', '-u', SCRIPT],
        env=env,
        capture_output=True,
        timeout=timeout,
    )
    # Forward the subprocess's own logging/print output to our stdout/stderr
    # regardless of success — otherwise it's captured and silently discarded,
    # and none of recovery_report.py's internal logging ever reaches Cloud Logging.
    stdout_text = result.stdout.decode(errors='replace')
    stderr_text = result.stderr.decode(errors='replace')
    if stdout_text:
        print(stdout_text, flush=True)
    if stderr_text:
        print(stderr_text, flush=True)
    if result.returncode != 0:
        err = (stderr_text or stdout_text)[-800:]
        raise RuntimeError(err)
    with open(out_path, 'rb') as f:
        return f.read()


def send_email(to: list[str], subject: str, filename: str, pdf_bytes: bytes) -> None:
    """Send PDF as attachment via Gmail SMTP using env-var credentials."""
    sender   = os.environ['GMAIL_SENDER']
    password = os.environ['GMAIL_APP_PASSWORD']

    msg = EmailMessage()
    msg['From']    = f'FSS Reports <{sender}>'
    msg['To']      = ', '.join(to)
    msg['Subject'] = subject
    msg.set_content(
        f'Please find attached: {filename}\n\nGenerated by FSS Reports.'
    )
    msg.add_attachment(pdf_bytes, maintype='application', subtype='pdf', filename=filename)

    with smtplib.SMTP_SSL('smtp.gmail.com', 465) as smtp:
        smtp.login(sender, password)
        smtp.send_message(msg)


def build_subject_and_filename(data: dict) -> tuple[str, str]:
    date_from    = data.get('dateFrom',  '2026-04-11')
    date_to      = data.get('dateTo',    '2026-04-18')
    deposit_to   = data.get('depositTo', '')
    institutions = data.get('institutions') or []
    institution  = data.get('institution',  '')

    inst_label   = ', '.join(institutions) if institutions else (institution or 'All Institutions')
    period_label = (f'{date_from} to {date_to} (deposits to {deposit_to})'
                    if deposit_to and deposit_to > date_to
                    else f'{date_from} to {date_to}')
    subject  = f'Recovery Methods Report — {inst_label} ({period_label})'
    filename = f'recovery-report-{date_from}-{date_to}.pdf'
    return subject, filename
